"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { createClient } from "@/lib/supabase/client";
import { useUser } from "@/components/providers/supabase-provider";

export function useGroups() {
  const supabase = createClient();
  return useQuery({
    queryKey: ["groups"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("groups")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
  });
}

export function useGroup(groupId: string | null) {
  const supabase = createClient();
  return useQuery({
    queryKey: ["groups", groupId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("groups")
        .select("*")
        .eq("id", groupId!)
        .single();
      if (error) throw error;
      return data;
    },
    enabled: !!groupId,
  });
}

export function useUserGroups() {
  const supabase = createClient();
  const { user } = useUser();
  return useQuery({
    queryKey: ["user_groups", user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("group_members")
        .select("group_id, role, joined_at, groups:group_id(id, name, description, invite_code)")
        .eq("user_id", user!.id)
        .order("joined_at", { ascending: true });
      if (error) throw error;
      return (data ?? []).map((m: any) => ({
        group_id: m.group_id,
        role: m.role as string,
        joined_at: m.joined_at as string,
        name: (m.groups as any)?.name ?? "Unknown",
        description: (m.groups as any)?.description as string | null,
        invite_code: (m.groups as any)?.invite_code as string | null,
      }));
    },
    enabled: !!user?.id,
  });
}

export function useUpdateGroup() {
  const supabase = createClient();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      groupId,
      updates,
    }: {
      groupId: string;
      updates: { name?: string; description?: string | null };
    }) => {
      const { data, error } = await supabase
        .from("groups")
        .update(updates)
        .eq("id", groupId)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["groups", data.id] });
      queryClient.invalidateQueries({ queryKey: ["groups"] });
      queryClient.invalidateQueries({ queryKey: ["user_groups"] });
    },
  });
}

export function useCreateGroup() {
  const supabase = createClient();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      name,
      description,
    }: {
      name: string;
      description?: string;
    }) => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      // Create the group (invite_code auto-generated by DB trigger)
      const { data: group, error: groupError } = await supabase
        .from("groups")
        .insert({ name, description })
        .select()
        .single();
      if (groupError) throw groupError;

      // Add creator as owner
      const displayName =
        user.user_metadata?.display_name || user.email?.split("@")[0] || "User";
      const { error: memberError } = await supabase
        .from("group_members")
        .insert({
          group_id: group.id,
          user_id: user.id,
          display_name: displayName,
          role: "owner",
        });
      if (memberError) throw memberError;

      return group;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["groups"] });
      queryClient.invalidateQueries({ queryKey: ["user_groups"] });
    },
  });
}

export function useDeleteGroup() {
  const supabase = createClient();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ groupId }: { groupId: string }) => {
      const { error } = await supabase
        .from("groups")
        .delete()
        .eq("id", groupId);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["groups"] });
      queryClient.invalidateQueries({ queryKey: ["user_groups"] });
      queryClient.invalidateQueries({ queryKey: ["group_members"] });
    },
  });
}

export function useLookupGroupByInviteCode() {
  const supabase = createClient();

  return useMutation({
    mutationFn: async (code: string) => {
      const { data, error } = await supabase.rpc("lookup_group_by_invite_code", {
        code: code.trim().toUpperCase(),
      });
      if (error) throw error;
      if (!data || (Array.isArray(data) && data.length === 0)) {
        throw new Error("No group found with that invite code");
      }
      const group = Array.isArray(data) ? data[0] : data;
      return group as { id: string; name: string; description: string | null; avatar_url: string | null };
    },
  });
}

export function useJoinGroup() {
  const supabase = createClient();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ groupId }: { groupId: string }) => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      // Check if already a member
      const { data: existing } = await supabase
        .from("group_members")
        .select("id")
        .eq("group_id", groupId)
        .eq("user_id", user.id)
        .single();

      if (existing) {
        return { group_id: groupId, already_member: true };
      }

      const displayName =
        user.user_metadata?.display_name || user.email?.split("@")[0] || "Member";
      const { error } = await supabase.from("group_members").insert({
        group_id: groupId,
        user_id: user.id,
        role: "member",
        display_name: displayName,
      });
      if (error) throw error;

      return { group_id: groupId, already_member: false };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["groups"] });
      queryClient.invalidateQueries({ queryKey: ["user_groups"] });
      queryClient.invalidateQueries({ queryKey: ["group_members"] });
    },
  });
}
